import uuid

def make_uid():
    return str(uuid.uuid4())

pcb_content = f"""(kicad_pcb
	(version 20260306)
	(generator "pcbnew")
	(generator_version "10.0")
	(general
		(thickness 1.6)
		(legacy_teardrops no)
	)
	(paper "A3")
	(title_block
		(title "Sony MHC-GN1300D 5.1 System Revival PCB")
		(date "2026-09-06")
		(rev "1.0")
		(company "Antigravity Engineering")
		(comment 1 "Lion Circuits 150x200mm 2-Layer FR4 1oz Copper")
	)
	(layers
		(0 "F.Cu" signal)
		(31 "B.Cu" signal)
		(32 "B.Adhes" user "B.Adhesive")
		(33 "F.Adhes" user "F.Adhesive")
		(34 "B.Paste" user)
		(35 "F.Paste" user)
		(36 "B.SilkS" user "B.Silkscreen")
		(37 "F.SilkS" user "F.Silkscreen")
		(38 "B.Mask" user)
		(39 "F.Mask" user)
		(40 "Dwgs.User" user "User.Drawings")
		(41 "Cmts.User" user "User.Comments")
		(42 "Eco1.User" user "User.Eco1")
		(43 "Eco2.User" user "User.Eco2")
		(44 "Edge.Cuts" user)
		(45 "Margin" user)
		(46 "B.CrtYd" user "B.Courtyard")
		(47 "F.CrtYd" user "F.Courtyard")
		(48 "B.Fab" user)
		(49 "F.Fab" user)
	)
	(setup
		(stackup
			(layer "F.SilkS" (type "Top Silk Screen") (color "White"))
			(layer "F.Paste" (type "Top Solder Paste"))
			(layer "F.Mask" (type "Top Solder Mask") (color "Green") (thickness 0.01))
			(layer "F.Cu" (type "copper") (thickness 0.035))
			(layer "dielectric 1" (type "core") (thickness 1.51) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))
			(layer "B.Cu" (type "copper") (thickness 0.035))
			(layer "B.Mask" (type "Bottom Solder Mask") (color "Green") (thickness 0.01))
			(layer "B.Paste" (type "Bottom Solder Paste"))
			(layer "B.SilkS" (type "Bottom Silk Screen") (color "White"))
			(copper_finish "HASL")
			(dielectric_constraints no)
		)
		(pad_to_mask_clearance 0.05)
		(pcbplotparams
			(layerselection 0x00010fc_ffffffff)
			(plot_on_all_layers_selection 0x0000000_00000000)
			(disableapertmacros no)
			(usegerberextensions yes)
			(usegerberattributes yes)
			(usegerberadvancedattributes yes)
			(creategerberjobfile yes)
			(dashed_line_dash_ratio 12.000000)
			(dashed_line_gap_ratio 3.000000)
			(svgprecision 4)
			(plotframeref no)
			(viasonmask no)
			(mode 1)
			(useauxorigin no)
			(hpglpennumber 1)
			(hpglpenspeed 20)
			(hpglpendiameter 15.000000)
			(pdf_front_fp_property_popups yes)
			(pdf_back_fp_property_popups yes)
			(dxfpolygonmode yes)
			(dxfimperialunits no)
			(dxfunits 0)
			(outputformat 1)
			(mirror no)
			(drillshape 1)
			(scaleselection 1)
			(outputdirectory "gerbers/")
		)
	)
	(net 0 "")
	
	(gr_rect (start 50 50) (end 250 200)
		(stroke (width 0.2) (type solid))
		(fill (type none))
		(layer "Edge.Cuts")
		(uuid "{make_uid()}")
	)
	
	(gr_text "SONY MHC-GN1300D 5.1 REVIVAL - REV 1.0"
		(at 150 58 0)
		(layer "F.SilkS")
		(uuid "{make_uid()}")
		(effects
			(font (size 2.5 2.5) (thickness 0.3))
			(justify center)
		)
	)
	(gr_text "Lion Circuits India - 150x200mm FR4"
		(at 150 63 0)
		(layer "F.SilkS")
		(uuid "{make_uid()}")
		(effects
			(font (size 1.5 1.5) (thickness 0.2))
			(justify center)
		)
	)
	
	(footprint "MountingHole:MountingHole_3.2mm_M3"
		(layer "F.Cu")
		(uuid "{make_uid()}")
		(at 56 56)
		(property "Reference" "H1" (at 0 -3 0) (effects (font (size 1 1)) (hide yes)))
		(property "Value" "MountingHole" (at 0 3 0) (effects (font (size 1 1)) (hide yes)))
		(pad "" np_thru_hole circle (at 0 0) (size 3.2 3.2) (drill 3.2) (layers "*.Cu" "*.Mask"))
	)
	(footprint "MountingHole:MountingHole_3.2mm_M3"
		(layer "F.Cu")
		(uuid "{make_uid()}")
		(at 244 56)
		(property "Reference" "H2" (at 0 -3 0) (effects (font (size 1 1)) (hide yes)))
		(property "Value" "MountingHole" (at 0 3 0) (effects (font (size 1 1)) (hide yes)))
		(pad "" np_thru_hole circle (at 0 0) (size 3.2 3.2) (drill 3.2) (layers "*.Cu" "*.Mask"))
	)
	(footprint "MountingHole:MountingHole_3.2mm_M3"
		(layer "F.Cu")
		(uuid "{make_uid()}")
		(at 244 194)
		(property "Reference" "H3" (at 0 -3 0) (effects (font (size 1 1)) (hide yes)))
		(property "Value" "MountingHole" (at 0 3 0) (effects (font (size 1 1)) (hide yes)))
		(pad "" np_thru_hole circle (at 0 0) (size 3.2 3.2) (drill 3.2) (layers "*.Cu" "*.Mask"))
	)
	(footprint "MountingHole:MountingHole_3.2mm_M3"
		(layer "F.Cu")
		(uuid "{make_uid()}")
		(at 56 194)
		(property "Reference" "H4" (at 0 -3 0) (effects (font (size 1 1)) (hide yes)))
		(property "Value" "MountingHole" (at 0 3 0) (effects (font (size 1 1)) (hide yes)))
		(pad "" np_thru_hole circle (at 0 0) (size 3.2 3.2) (drill 3.2) (layers "*.Cu" "*.Mask"))
	)
)
"""

with open("hardware/sony-5.1-revival/sony-5.1-revival.kicad_pcb", "w") as f:
    f.write(pcb_content)

print("Generated hardware/sony-5.1-revival/sony-5.1-revival.kicad_pcb")
